TRAIN:
  train_batch_size: 32  
  lr: 0.0003

  valid_batch_size: 8

  image_size: [224,224]

  min_epochs: 20
  max_epochs: 200
  patience: 20

  device: [0]

  model_save_path: ./save_model
  model_save_filename: medseg

MODEL:
  bert_type: ../lib/BiomedVLP-CXR-BERT-specialized               
  vision_type: ../lib/convnext-tiny-224         
  project_dim: 768

DATA:
  train_csv_path_0: ../data/QaTa-COV19-v2/prompt/train.csv  
  train_root_path_0: ../data/QaTa-COV19-v2/Train 

  train_csv_path_1: ../data/MosMed/prompt/train.csv   
  train_root_path_1: ../data/MosMed/Train

  test_csv_path_0: ../data/QaTa-COV19-v2/prompt/test.csv 
  test_root_path_0: ../data/QaTa-COV19-v2/Test

  test_csv_path_1: ../data/MosMed/prompt/test.csv
  test_root_path_1: ../data/MosMed/Test


